apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: muchtodo
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - name: mongo
              containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          readinessProbe:
            exec:
              command: ["mongosh", "--eval", "db.runCommand({ ping: 1 })"]
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            exec:
              command: ["mongosh", "--eval", "db.runCommand({ ping: 1 })"]
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
